name: WarGame
main: yar.wargame.hu.Main
version: 1.2.0
api-version: 1.19
api: 1.19.3
commands:
 placecannon:
  aliases: [pc]
  description: place a cannon
 wargame:
  aliases: [wg]
  description: wargame commands
 kit:
  description: kit command
 equipment:
  description: equipment
 kits:
  description: open the kits
